SELECT 
    o.order_uid,
    o.track_number,
    o.entry,
    o.locale,
    o.internal_signature,
    o.customer_id,
    o.delivery_service,
    o.shardkey,
    o.sm_id,
    o.date_created,
    o.oof_shard,
    d.name as delivery_name,
    d.phone as delivery_phone,
    d.zip as delivery_zip,
    d.city as delivery_city,
    d.address as delivery_address,
    d.region as delivery_region,
    d.email as delivery_email,
    p.transaction as payment_transaction,
    p.request_id as payment_request_id,
    p.currency as payment_currency,
    p.provider as payment_provider,
    p.amount as payment_amount,
    p.payment_dt as payment_payment_dt,
    p.bank as payment_bank,
    p.delivery_cost as payment_delivery_cost,
    p.goods_total as payment_goods_total,
    p.custom_fee as payment_custom_fee,
    json_agg(
        json_build_object(
            'chrt_id', i.chrt_id,
            'track_number', i.track_number,
            'price', i.price,
            'rid', i.rid,
            'name', i.name,
            'sale', i.sale,
            'size', i.size,
            'total_price', i.total_price,
            'nm_id', i.nm_id,
            'brand', i.brand,
            'status', i.status
        )
    ) as items
FROM orders o
JOIN delivery d ON o.delivery_id = d.delivery_id
JOIN payment p ON o.payment_id = p.payment_id
JOIN orders_items oi ON o.order_uid = oi.order_uid
JOIN items i ON oi.item_id = i.items_id
WHERE o.order_uid = $1
GROUP BY 
    o.order_uid, 
    o.track_number, 
    o.entry, 
    o.locale, 
    o.internal_signature, 
    o.customer_id, 
    o.delivery_service, 
    o.shardkey, 
    o.sm_id, 
    o.date_created, 
    o.oof_shard,
    d.name,
    d.phone,
    d.zip,
    d.city,
    d.address,
    d.region,
    d.email,
    p.transaction,
    p.request_id,
    p.currency,
    p.provider,
    p.amount,
    p.payment_dt,
    p.bank,
    p.delivery_cost,
    p.goods_total,
    p.custom_fee;